### ISSUE TITLE
The tainted cain controls wont work.

### ISSUE THREAD

**Issue by Sovietsupporter69** [Zamiell/isaac-mod-config-menu#18]
Exactly as the title says I can't get the tainted Cain (or more specifically the bag of crafting) controls wont work, I've tested if other mods effect it but after disabling all other mods I it still doesn't work. The things I do know are bellow:
 - I'm on the most recent update (as of 14/12/22)
 - The rest of the mod seems to be working fine
 - Apart from the controls (of which none but the turn of and on are working) the BoC menu is working and giving me the right items

If you need any specifics from me I would be willing to provide them so long as they will help reach a conclusion.

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by Sovietsupporter69** [comment]
Whats a pr? not that familiar with git hub

**Comment by Sovietsupporter69** [comment]
Also another note I've got 2 PCs and the second one works fine so it might be hardware dependent thing.

**Comment by Zamiell** [comment]
a pull request

**Comment by Sovietsupporter69** [comment]
It seems to have been a hardware issue as by changing my keyboard the issue was resolved.
