### ISSUE TITLE
Mod Menu not saving settings upon close

### ISSUE THREAD

**Issue by qoolguy** [Zamiell/isaac-mod-config-menu#20]
specifically with soundtrack menu, changes made to settings reset upon game close. mods like minimap api keep settings though

**Comment by Zamiell** [comment]
Mod Config Menu Pure is not responsible for saving the configuration data of other mods. Doing that is up to the other mods. Thus, if another mod's settings are not being properly saved, then you need to take that issue to the specific mod's developer.
