### ISSUE TITLE
F10 doesn't open menu after full reinstall and solo mod installation

### ISSUE THREAD

**Issue by Ravannos** [Zamiell/isaac-mod-config-menu#22]
Any attempt to make Mod Config Menu - Pure has ended in failure. The following have been attempted:
- clean re-install of BoI Repentance
- MCM Pure being the only active mod
- clean full re-install of Steam
- deactivation of vJoy device
- deactivation of reWASD
- attempt to use virtual keyboard to trigger menu
- several restarts in between all these steps.
All end in mod menu not being able to be opened by F10, L, or Right Stick button 

The only clue I could get is a warning message from the log.txt:
`[INFO] - [warn] AnmCache: cannot remove reference to gfx/ui/modconfig/menu.anm2`
Attached is the log.txt
[log.txt](https://github.com/Zamiell/isaac-mod-config-menu/files/15137700/log.txt)

Hoping for help in debugging this on my end.

**Comment by Zamiell** [comment]
it has to be you because it works fine for everybody else

**Comment by JustASysAdmin** [comment]
Perhaps it's some kind of mod conflict because I have the same issue. I don't know. 
![image](https://github.com/Zamiell/isaac-mod-config-menu/assets/97370685/1efdf910-7858-4f42-8a25-0342fa318407)

**Comment by Zamiell** [comment]
use binary search to find the conflicting mod

**Comment by Ravannos** [comment]
Unfortunately, it seems mod incompatibility is not the reason for my end. I have tested the mod all by itself, and with 1 mod, [Watch out, laser!]. which mentions the pure version of Mod Config Menu explicitly in the description. Neither worked

I have tested the older discontinued [Continued] version of this mod, both on Repentance and Afterbirth+, and that older mod also does not register F10 or the L key.

Due to this and other slight factors to my desktop, I have reset the Windows 10 installation. Oddly enough, the problem persists both for Pure and Continued.

Another factor I tested is the keyboard itself, with alternate keyboards, wired and wireless, and even the On-Screen Virtual Keyboard. None of their F10s and L keys managed to trigger either of the versions' menus.

At this point, I don't know what else could be the cause of the problem. I somewhat suspect the Steam Cloud Saves, and I am currently trying to test that, either by attempting to delete all BoI related cloud saves, or trying a pirated copy.
I am currently working on the first option. I dont know if you mod will work on a pirated version honestly, but I'd rather test out a pirated version first before buying a whole new game on a different alternate account.

Final scorched-earth solution is to completely reformat my C: Drive and reinstall Windows. Kinda overkill, but I have been meaning to try Windows 11. Now could be a good chance.

Do you have any opinions or insights with my methods Mr. Mod Author?
While I'm here, I'd also like to ask which file and which line of code of the Pure mod I could change to edit the key press needed to trigger the sub-menu. I'd like to hook it to something else for testing, like mouse click even. Maybe the problem is inability to register input. Bit of a stretch really, but sadly my options have dwindled.

**Comment by Ravannos** [comment]
Good news, I finally fixed it. Granted, I did not know what I exactly did that truly fixed it.
But I did succeed in purging all old files loaded by Steam Cloud Save, so I'm guessing something from my very old runs of BoI was the cause.
Note: If you wish to stop Cloud Save for Binding of Isaac, you need to manually edit _SteamCloud=1_ in the options.ini found the My Games folder of your Documents. Change the 1 into a 0. Disabling local and account wide cloud save did not stop cloud save for Binding of Isaac, you must change that line yourself.
Additionally, if you have OneDrive, Binding of Isaac is not in the OneDrive Documents, it's in the Documents folder of your User Folder.

**Comment by CaptainPetrvoi4** [comment]
I too have found a solution to this problem. I had this menu did not open through "L" and "F10". I looked in log.txt and reinstalled the mod - nothing helped, even changing SteamCloud to 0 in options.ini and I remembered that I have in Nvidia GeForce Experience on "F10" save the last 5 minutes and when I reassigned this key in Nvidia, oh my God, I have Mod Config opened through F10!😅
