### ISSUE TITLE
Console keep logging error when window size is odd number

### ISSUE THREAD

**Issue by 58115310** [Zamiell/isaac-mod-config-menu#5]
![QQ截图20220127211112](https://user-images.githubusercontent.com/22266114/151365815-dbe37701-a2d8-4d76-8cf1-edb86079d8b6.png)
looks like a DrawString parameter needs an integer, not a float

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by Zamiell** [comment]
#6
